sensors:
  imu_node:
    ros__parameters:
      pub_rate_hz: 100

      i2c_bus: 1
      use_alternate_i2c_addr: false

      enable_orientation: false
      enable_accel: true
      enable_gyro: true
      enable_mag: true

      imu_data_topic: imu/imu
      mag_data_topic: imu/mag

      link: temp_humid_sensor_link
