comms:
  webrtc_node:
    ros__parameters:
      pub_rate_hz: 50

      webgui_path: /webgui
      sdp_gathering_timeout_ms: 5000

      pose_topic: rov/pose
      twist_topic: rov/twist
      accel_topic: rov/accel
      pressure_topic: pressure/pressure
      exterior_temp_topic: pressure/temp
      interior_temp_topic: temphumid/temp
      relative_humidity_topic: temphumid/humid
